comubu:
    resource: "@ComubuBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    defaults:
        _format: json
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register
