<?php

namespace ComubuBundle\Repository;

use ComubuBundle\Entity\User;
use ComubuBundle\Entity\Hero;

/**
 * HeroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeroRepository extends \Doctrine\ORM\EntityRepository
{
    public function getHeroesByUser(User $user){
        return $this->getEntityManager()->createQueryBuilder()
            ->select('h')
            ->from('ComubuBundle:Hero', 'h')
            ->join('h.user', 'u')
            ->addSelect('u')
            ->where('u.id = :id')
            ->setParameter('id', $user->getId())
            ->andWhere('h.state = :ok OR h.state = :selected')
            ->setParameter('ok', Hero::STATUS_OK)
            ->setParameter('selected', Hero::STATUS_SELECTED)
            ->getQuery()
            ->getResult();
    }
}
